### ISSUE TITLE
may be a bug for Sysy.g4

### ISSUE THREAD

**Issue by zhiqiangzz** [Gaomengkai/Vrabche#7]
may be you should replace lAndExp with follow
```
lAndExp:
	eqExp					# lAndExp_
	| lAndExp And eqExp		# and
	| Lparen lOrExp Rparen	        # lAndExp_;
```

**Comment by Gaomengkai** [comment]
language definition
https://gitlab.eduxiji.net/nscscc/compiler2023/-/blob/master/SysY2022%E8%AF%AD%E8%A8%80%E5%AE%9A%E4%B9%89-V1.pdf
